# Generated by Django 5.2.8 on 2025-11-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beneficios', models.TextField()),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
    ]
