# Generated by Django 5.2.8 on 2025-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
